# Generated by Django 3.2 on 2021-08-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('texto_tweet', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=20)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=20)),
                ('imagen_link', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
